name: siddhesh

on: 
   push: 
    branches: [main]

jobs:
    ang:
     runs-on: [ubuntu-latest]

     steps:
         - name: cheking
           run: echo "Hi i am siddhesh"
     steps:
        - name: Planning
          run: echo "plan the next step"
    
